### PR TITLE
build.sh: add build options through environment variables

### PR DESCRIPTION
**Pull request by dbermond**
This will easily allow the user to toggle some build-time options. Useful for packaging.

This will not change the default settings, and will just add the possibility to change some options.

Fell free to close if this is not desired or if this looks weird in someway :)

### CODE REVIEW

**Comment by loganmc10** [comment]
Thanks, I'm going to pass on this one, building with these options set the way they are is part of the m64p package

**Comment by dbermond** [comment]
Enabling assembly optimizations on mupen64plus components and HQ on GLideN64 can cause any problems when running m64p?

**Comment by loganmc10** [comment]
Correct

**Comment by dbermond** [comment]
Can you please elaborate? Will it break something?

It works fine for me with these optimizations enabled.

**Comment by loganmc10** [comment]
This project isn't a build script for building mupen64plus. It's a product, with releases available at https://github.com/loganmc10/m64p/releases, the changes don't do anything for the releases, since they are built without those flags

**Pull request closed without merging**
